# Generated by Django 4.2.23 on 2026-06-04 20:50

from django.db import migrations, models
import guarda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('responsavel', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('paroquia', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guarda',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idguarda', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField(unique=True)),
                ('turma', models.IntegerField(blank=True, null=True)),
                ('matricula_padrinho', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=guarda.models.foto_upload_path)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('rg', models.CharField(blank=True, max_length=45, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('separado', 'Separado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('celular', models.CharField(blank=True, max_length=45, null=True)),
                ('tel_comercial', models.CharField(blank=True, max_length=45, null=True)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('UF', models.CharField(blank=True, max_length=2, null=True)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Guarda',
            },
        ),
    ]
