# Generated by Django 4.2.23 on 2026-06-04 20:41

from django.db import migrations, models
import django.db.models.deletion
import guarda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_ingresso', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GUARDA',
            },
        ),
        migrations.CreateModel(
            name='GuardaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('responsavel', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('paroquia', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=guarda.models.foto_upload_path)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PESSOA',
            },
        ),
        migrations.CreateModel(
            name='Sacramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batismo', models.BooleanField(default=False)),
                ('eucaristia', models.BooleanField(default=False)),
                ('crisma', models.BooleanField(default=False)),
                ('matrimonio', models.BooleanField(default=False)),
                ('data_batismo', models.DateField(blank=True, null=True)),
                ('data_eucaristia', models.DateField(blank=True, null=True)),
                ('data_crisma', models.DateField(blank=True, null=True)),
                ('guarda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guarda.guarda')),
            ],
            options={
                'db_table': 'SACRAMENTO',
            },
        ),
        migrations.AddField(
            model_name='guarda',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='guarda.pessoa'),
        ),
        migrations.CreateModel(
            name='FichaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tipoSanguineo', models.CharField(blank=True, max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('doenca_cronica', models.TextField(blank=True, null=True)),
                ('medicamento_continuo', models.TextField(blank=True, null=True)),
                ('restricao_alimentar', models.TextField(blank=True, null=True)),
                ('plano_saude', models.CharField(blank=True, max_length=100, null=True)),
                ('contato_emergencia', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('guarda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='guarda.guarda')),
            ],
            options={
                'db_table': 'FICHA_SAUDE',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco_obj', to='guarda.pessoa')),
            ],
            options={
                'db_table': 'ENDERECO',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('pessoa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='guarda.pessoa')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelGuarda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='guarda.guarda')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guarda.pessoa')),
            ],
            options={
                'db_table': 'RESPONSAVEL_GUARDA',
                'unique_together': {('guarda', 'pessoa')},
            },
        ),
        migrations.CreateModel(
            name='PadrinhoGuarda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padrinhos', to='guarda.guarda')),
                ('padrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afilhados', to='guarda.guarda')),
            ],
            options={
                'db_table': 'PADRINHO_GUARDA',
                'unique_together': {('guarda', 'padrinho')},
            },
        ),
    ]
