# Generated by Django 4.2.23 on 2026-05-02 19:02

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarda',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idguarda', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField(unique=True)),
                ('turma', models.IntegerField(blank=True, null=True)),
                ('matricula_padrinho', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=app.models.foto_upload_path)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('rg', models.CharField(blank=True, max_length=45, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('separado', 'Separado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=45, null=True)),
                ('celular', models.CharField(blank=True, max_length=45, null=True)),
                ('tel_comercial', models.CharField(blank=True, max_length=45, null=True)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('UF', models.CharField(blank=True, max_length=2, null=True)),
                ('encoding', models.BinaryField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Guarda',
            },
        ),
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('equipe', models.CharField(max_length=15)),
                ('situacao', models.BooleanField()),
                ('tamcamisa', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G'), ('6G', '6G')], max_length=2)),
                ('recebido', models.BooleanField()),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to=app.models.termo_upload_path)),
                ('procuracao', models.FileField(blank=True, null=True, upload_to=app.models.procuracao_upload_path)),
                ('recebedor', models.CharField(blank=True, max_length=45, null=True)),
                ('data', models.DateTimeField()),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camisas_criadas', to=settings.AUTH_USER_MODEL)),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camisas_entregues', to=settings.AUTH_USER_MODEL)),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camisas_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camisa',
            },
        ),
        migrations.CreateModel(
            name='GuardaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=7)),
                ('responsavel', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('paroquia', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CamisaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_antigo', models.CharField(max_length=5)),
                ('tamanho_novo', models.CharField(max_length=5)),
                ('situacao_antiga', models.CharField(max_length=10)),
                ('situacao_nova', models.CharField(max_length=10)),
                ('equipe_antiga', models.CharField(blank=True, max_length=15, null=True)),
                ('equipe_nova', models.CharField(blank=True, max_length=15, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.camisa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camisa_log',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='CamisaGuardaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G'), ('6G', '6G')], max_length=2)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('recebido', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('apoio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camisas', to='app.guardaapoio')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apoio_entregues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('apoio', 'tamanho')},
            },
        ),
    ]
