# Generated by Django 4.2.23 on 2026-06-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('is_funcionario', models.BooleanField(default=False)),
                ('is_super_usuario', models.BooleanField(default=False)),
                ('is_ativo', models.BooleanField(default=True)),
                ('trocar_senha', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='pessoa.pessoa')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
    ]
