# Generated by Django 4.2.23 on 2026-06-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCirio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Categoria do Círio',
                'verbose_name_plural': 'Categorias do Círio',
                'db_table': 'CATEGORIA_CIRIO',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cirio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Círio',
                'verbose_name_plural': 'Círios',
                'db_table': 'CIRIO',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='RegraCirio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cirio.categoriacirio')),
                ('cirio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='cirio.cirio')),
            ],
            options={
                'verbose_name': 'Regra do Círio',
                'verbose_name_plural': 'Regras do Círio',
                'db_table': 'REGRA_CIRIO',
                'unique_together': {('cirio', 'categoria')},
            },
        ),
    ]
