# Generated by Django 4.2.23 on 2026-06-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Evento',
                'verbose_name_plural': 'Categorias de Evento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cirio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Círio',
                'verbose_name_plural': 'Círios',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='GuardaMirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mirim/fotos/')),
                ('responsavel_nome', models.CharField(blank=True, max_length=200)),
                ('responsavel_contato', models.CharField(blank=True, max_length=50)),
                ('parentesco_responsavel', models.CharField(blank=True, choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Outro', 'Outro')], max_length=10)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tamanho_camisa', models.CharField(blank=True, choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=3)),
                ('autismo_tdah_alergia', models.CharField(blank=True, max_length=200)),
                ('intolerancia_alimentar', models.CharField(blank=True, max_length=200)),
                ('doenca_cronica', models.CharField(blank=True, max_length=200)),
                ('uso_medicamento_controlado', models.CharField(blank=True, max_length=200)),
                ('observacoes_pais', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guarda Mirim',
                'verbose_name_plural': 'Guardas Mirins',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='mirim.categoriaevento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='mirim.local')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-hora'],
                'unique_together': {('categoria', 'local', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='RegraCirio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mirim.categoriaevento')),
                ('cirio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='mirim.cirio')),
            ],
            options={
                'verbose_name': 'Regra do Círio',
                'verbose_name_plural': 'Regras do Círio',
                'unique_together': {('cirio', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por_reconhecimento_facial', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='mirim.evento')),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='mirim.guardamirim')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['-data_registro'],
                'unique_together': {('guarda', 'evento')},
            },
        ),
    ]
