# Generated by Django 4.2.23 on 2026-06-04 20:41

import camisa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('equipe', models.CharField(max_length=15)),
                ('situacao', models.BooleanField()),
                ('tamcamisa', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G'), ('6G', '6G')], max_length=2)),
                ('recebido', models.BooleanField()),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to=camisa.models.termo_upload_path)),
                ('procuracao', models.FileField(blank=True, null=True, upload_to=camisa.models.procuracao_upload_path)),
                ('recebedor', models.CharField(blank=True, max_length=45, null=True)),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'camisa',
            },
        ),
        migrations.CreateModel(
            name='CamisaGuardaApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G'), ('6G', '6G')], max_length=2)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('recebido', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CamisaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_antigo', models.CharField(max_length=5)),
                ('tamanho_novo', models.CharField(max_length=5)),
                ('situacao_antiga', models.CharField(max_length=10)),
                ('situacao_nova', models.CharField(max_length=10)),
                ('equipe_antiga', models.CharField(blank=True, max_length=15, null=True)),
                ('equipe_nova', models.CharField(blank=True, max_length=15, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='camisa.camisa')),
            ],
            options={
                'db_table': 'camisa_log',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
