# Generated by Django 4.2.23 on 2026-06-04 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guarda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('tamanho_camisa', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('3G', '3G'), ('4G', '4G'), ('5G', '5G'), ('6G', '6G')], max_length=10)),
                ('situacao', models.BooleanField(default=False)),
                ('recebido', models.BooleanField(default=False)),
                ('recebedor', models.CharField(blank=True, max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camisas_criadas', to='guarda.guarda')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='camisas_entregues', to='guarda.guarda')),
            ],
            options={
                'db_table': 'CAMISA',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EQUIPE',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CamisaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_antigo', models.CharField(blank=True, max_length=10, null=True)),
                ('tamanho_novo', models.CharField(blank=True, max_length=10, null=True)),
                ('situacao_antiga', models.BooleanField(blank=True, null=True)),
                ('situacao_nova', models.BooleanField(blank=True, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=200, null=True)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('camisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='camisa.camisa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CAMISA_LOG',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.AddField(
            model_name='camisa',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camisas', to='camisa.equipe'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='guarda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camisas_recebidas', to='guarda.guarda'),
        ),
    ]
