# Generated by Django 4.2.23 on 2026-06-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guarda', '0001_initial'),
        ('camisa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camisalog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guarda.guarda'),
        ),
        migrations.AddField(
            model_name='camisaguardaapoio',
            name='apoio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camisas', to='guarda.guardaapoio'),
        ),
        migrations.AddField(
            model_name='camisaguardaapoio',
            name='entregador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apoio_entregues', to='guarda.guarda'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camisas_criadas', to='guarda.guarda'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='entregador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camisas_entregues', to='guarda.guarda'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='guarda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='camisas_recebidas', to='guarda.guarda'),
        ),
        migrations.AlterUniqueTogether(
            name='camisaguardaapoio',
            unique_together={('apoio', 'tamanho')},
        ),
    ]
