# Generated by Django 4.2.23 on 2026-06-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autismo', models.BooleanField(default=False)),
                ('tdah', models.BooleanField(default=False)),
                ('alzheimer', models.BooleanField(default=False)),
                ('demencia', models.BooleanField(default=False)),
                ('parkinson', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertensao', models.BooleanField(default=False)),
                ('problema_cardiaco', models.BooleanField(default=False)),
                ('problema_renal', models.BooleanField(default=False)),
                ('osteoporose', models.BooleanField(default=False)),
                ('artrite', models.BooleanField(default=False)),
                ('usa_cadeira_rodas', models.BooleanField(default=False)),
                ('usa_andador', models.BooleanField(default=False)),
                ('usa_bengala', models.BooleanField(default=False)),
                ('deficiencia_visual', models.BooleanField(default=False)),
                ('deficiencia_auditiva', models.BooleanField(default=False)),
                ('usa_protese', models.BooleanField(default=False)),
                ('depressao', models.BooleanField(default=False)),
                ('ansiedade', models.BooleanField(default=False)),
                ('alergia', models.CharField(blank=True, max_length=250, null=True)),
                ('intolerancia_alimentar', models.CharField(blank=True, max_length=250, null=True)),
                ('doenca_cronica', models.CharField(blank=True, max_length=250, null=True)),
                ('uso_medicamento_controlado', models.CharField(blank=True, max_length=250, null=True)),
                ('plano_saude', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=150, null=True)),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=200, null=True)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_saude', to='pessoa.pessoa')),
            ],
            options={
                'db_table': 'FICHA_SAUDE',
            },
        ),
    ]
