# Generated by Django 4.2.23 on 2026-06-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guarda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Evento',
                'verbose_name_plural': 'Categorias de Evento',
                'db_table': 'CATEGORIA_EVENTO',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'db_table': 'LOCAL',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('is_frequencia_autorizada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='evento.categoriaevento')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='evento.local')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'EVENTO',
                'ordering': ['-data', '-hora'],
                'unique_together': {('categoria', 'local', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('reconhecimento_facial', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='evento.evento')),
                ('guarda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='guarda.guarda')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'db_table': 'FREQUENCIA',
                'ordering': ['-data_registro'],
                'unique_together': {('guarda', 'evento')},
            },
        ),
    ]
